using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Айдар
{
public partial class Form1 : Form
{
double buffer;//sum
bool Sum = false;//sum
bool minus = false;
bool ymnoshenie = false;
bool delenie = false;
bool Point = false;




public Form1()
{
InitializeComponent();
}

private void Form1_Load(object sender, EventArgs e)
{


}

private void button1_Click(object sender, EventArgs e)
{
label1.Text += "1";
}

private void button7_Click(object sender, EventArgs e)
{
label1.Text += "2";
}

private void button8_Click(object sender, EventArgs e)
{
label1.Text = "";
label1.Tag = "";
}

private void button2_Click(object sender, EventArgs e)
{
label1.Text += "3";
}

private void button6_Click(object sender, EventArgs e)
{
label1.Text += "7";
}

private void button4_Click(object sender, EventArgs e)
{
label1.Text += "5";
}

private void button3_Click(object sender, EventArgs e)
{
label1.Text += "4";
}

private void button5_Click(object sender, EventArgs e)
{
label1.Text += "6";
}

private void button12_Click(object sender, EventArgs e)
{
label1.Text += "8";
}

private void button11_Click(object sender, EventArgs e)
{
label1.Text += "9";
}

private void button9_Click(object sender, EventArgs e)
{
label1.Text += "0";
}

private void button10_Click(object sender, EventArgs e)
{
buffer = double.Parse(label1.Text);
label1.Text = "";
Sum = true;
}

private void label1_Click(object sender, EventArgs e)
{
buffer = double.Parse(label1.Text);
label1.Text = "";
Sum = true;
}

private void button13_Click(object sender, EventArgs e)
{

buffer = double.Parse(label1.Text);
label1.Text = "";
minus = true;

}

private void button15_Click(object sender, EventArgs e)
{
buffer = double.Parse(label1.Text);
label1.Text = "";
delenie = true;
}

private void button16_Click(object sender, EventArgs e)
{
if (Sum == true) buffer = buffer + double.Parse(label1.Text);
if (delenie == true) buffer = buffer / double.Parse(label1.Text);
if (ymnoshenie == true) buffer = buffer * double.Parse(label1.Text);
if (minus == true) buffer = buffer - double.Parse(label1.Text);
label1.Text = buffer.ToString();
}

private void button14_Click(object sender, EventArgs e)
{
buffer = double.Parse(label1.Text);
label1.Text = "";
ymnoshenie = true;

}

private void button17_Click(object sender, EventArgs e)
{
double x;
x = Convert.ToDouble(label1.Text) * Convert.ToDouble(label1.Text);
label1.Text = Convert.ToString(x);
}

private void button18_Click(object sender, EventArgs e)
{
if(Point==false)
{
Point = true;
label1.Text += ",";
}
}

private void button19_Click(object sender, EventArgs e)
{

}
}
}